### ISSUE TITLE
Long videos do not play

### ISSUE THREAD

**Issue by scrubb** [ear9mrn/MythRokuPlayer#14]
I have the system up and running very nicely on a mythbuntu 11.04 install and a Roku 2 XS.
I can browse my converted videos and select play.
It seems that short videos (30min or less) will play.
When I attempt to play longer videos such as 1 hour, the screen blinks and flips back to the item play menu.  

In troubleshooting it seems that no mp4 player I have can play the mp4's created by the rokuencode.sh unless I have copied the whole file from mythweb.  The errors I am receiving are about not finding the moov atom.  Some research seems to indicate that mp4s put the atom at the end unless its been re-indexed to the front.  This may not be the issue bu this is the only clue I have been able to assemble as to why this is not working.

Please let me know if there is a way I can gather more information for this issue or if this is known.
Thank you!

**Comment by mchasal** [comment]
This link suggests the option you can add to the handbrake call to have it put the atom in the front: http://webvideo.wikischolars.columbia.edu/H.264+HTTP+Web+Notes

Give that a try and see if it helps. I've had this error, but only once when something went wrong with the encode.

**Comment by rshendershot** [comment]
the conversion can produce artefacts, even some that manifest as bugs. A good next step is to provide the conversion command.

**Comment by scrubb** [comment]
rshendershot, I am using the rokuencode.sh file included in the mythroku code. (and its included handbrakecli command)

mchasal, I have added the -O to the handbrakecli line in the rokuencode.sh file (optimize for web streaming) and am re-encoding one of the longer files to see if that addresses the issue.  I will report back if that resolves it.
Thank you.

**Comment by zane131** [comment]
All of my videos have been converted using Handbrake with the "Normal" or "High Profile" presets and I have not had any issues with streaming to my Rokus. I have never actually use rokuencode.sh. I hope this help narrow your focus.

**Comment by scrubb** [comment]
I confirmed that the -O parameter for handbrake seems to have resolved my playback issues for longer files.  It might be recommended to update the rokuencode.sh script to include this by default.
Thank you all for helping resolve this.

**Comment by rshendershot** [comment]
scrubb - are you using HD or SD playback?  I use SD and, like the others, have not had this problem on either Roku or Roku 2 devices.  One difference is that I use the 'iPhone & iPod Touch' which does cut back on size/quality of the recording and might be masking the problem or contributing to hiding it.

**Comment by scrubb** [comment]
SD playback, but the file is HD to start with.  Indeed, the 30 min or less files seemed to have no problem with the rokuencode.sh as it was, it was the longer ones that had issues.

I did a little more reading and it looks like ffmpeg will also create mp4s with atoms in the front and throughout so it might be possible to start streaming a file before it's finished converting, possibly to allow watching of a show while it's recording.  If I get that far, I'll share any scripts, etc that I come up with.
Thanks again all.

**Comment by rshendershot** [comment]
I think this is resolved.  I don't think adding that flag is necessary for the general case.  if it comes up again we can reopen.
