### ISSUE TITLE
use mythtv's built in transcoding instead of HandbrakeCLI

### ISSUE THREAD

**Issue by mspiceland** [ear9mrn/MythRokuPlayer#15]
Currently MythRokuPlayer requires HandbrakeCLI and the rekuencode.sh to encode video files.  It would be great if it was able to use mythtv's bult in transcoding, so nothing extra was needed.  Did you test with this?  Is there a reason why it won't generate proper h264 files for the Roku?

This would make things one step closer to be easy to install.  I'm hoping that one day you'll be able to package the php portions as a simple .deb and .rpm packages so that one just installs them alongside the distros mythtv packages with nothing else to do.  I think a lot more people would use your work that way.

**Comment by zane131** [comment]
I rarely use mythtranscode. Does it transcode to h.264 format? Does it have the ability to convert pretty much every other file format into h.264 like Handbrake does?

**Comment by mspiceland** [comment]
zane131, I don't know.  I was hoping that ear9mm might know :-)
