### ISSUE TITLE
Delete deletes all same-time recordings

### ISSUE THREAD

**Issue by mchasal** [ear9mrn/MythRokuPlayer#4]
I just found this problem and wanted to let you know about it, I'll be working on a fix, so I'll let you know when I come up with that.

The problem is that the delete function uses the starttime as the key to delete recordings from the DB. This causes it to delete ALL recordings that started at that time. Not a problem if you have only one tuner, but definitely one if you have multiple tuners.

**Comment by ear9mrn** [comment]
the base name consists of start time in epoch and channel number so we can just changes to the search for base name.

**Comment by mchasal** [comment]
Looks like there's a problem with the committed patch. Check the thread on the Roku Forum. RemoveExtension was removed,  but it's still being called elsewhere in the file.

**Comment by ear9mrn** [comment]
OK, sorry about that, doing stuff in a hurry and thought I was being tidy by removing it and not checking my work thoroughly. Thanks for reporting it.

Put it a back so should be fixed, now.
